//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.LicenseServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKey
    {
        public int Id { get; set; }
        public string ApiKey1 { get; set; }
        public string ClientId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual LicenseOwner LicenseOwner { get; set; }
    }
}
