//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.LicenseServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseActivation
    {
        public int Id { get; set; }
        public System.Guid LicenseId { get; set; }
        public string ComputerId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ComputerCount { get; set; }
        public string ComputerName { get; set; }
        public string DiskNumCr { get; set; }
        public string RegUserNameCr { get; set; }
        public Nullable<int> LicenseOwnerServerId { get; set; }
    
        public virtual License License { get; set; }
    }
}
