//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.LicenseServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.LicenseModules = new HashSet<LicenseModule>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool IsDemo { get; set; }
        public int LicenseOwnerId { get; set; }
    
        public virtual ICollection<LicenseModule> LicenseModules { get; set; }
        public virtual LicenseOwner LicenseOwner { get; set; }
    }
}
