//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.LicenseServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicensesLog
    {
        public int Id { get; set; }
        public System.Guid LicenseId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDemo { get; set; }
        public string Changes { get; set; }
        public int ChangeType { get; set; }
    }
}
