//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.LicenseServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseOwnerServer
    {
        public int LicenseOwnerID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ServerInstance { get; set; }
        public string ServerIPAddress { get; set; }
        public string SendFromPC { get; set; }
        public string SendFromPCIPAddress { get; set; }
        public string SystemUserName { get; set; }
    }
}
