//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.LicenseServer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        public Licenses()
        {
            this.LicenseModules = new HashSet<LicenseModules>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool IsDemo { get; set; }
    
        public virtual ICollection<LicenseModules> LicenseModules { get; set; }
        public virtual LicenseOwners LicenseOwner { get; set; }
    }
}
